### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException due to bad forwardURI?

### ISSUE THREAD

**Issue by dstieglitz** [pledbrook/grails-shiro#57]
Hi folks:

We are experiencing a strange error after having deployed our app to a new environment. It must be related to the configuration of the server but it's presenting as an exception from the GrailsShiroPlugin. ShiroGrailsPlugin.groovy:440 is the line that separates the forwardURI from the context. In this case we have the app deployed on the root context.

Note that this deployment works well in our development environment, but not in the target cluster, and we're looking for assistance in helping to debug the environment (or if anyone has seen this before)?

Dan

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
        at java.lang.String.substring(String.java:1907)
        at ShiroGrailsPlugin.accessControlMethod(ShiroGrailsPlugin.groovy:440)
        at ShiroGrailsPlugin$_closure3$_closure24.doCall(ShiroGrailsPlugin.groovy:236)
        at x.x.x.SecurityFilters$_closure1$_closure5$_closure9.doCall(SecurityFilters.groovy:100)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by dstieglitz** [comment]
If anyone is interested, this occurred for us on Tomcat when the app was deployed in the ROOT context, using a context path of '/'. The correct context path is ''.

I'm not sure if the library should catch this and react, or if this error response is sufficient-- it certainly causes you to debug the issue but there's not really any useful information here.

What is also strange is that the string index of '2' doesn't seem to fit with the forwardURI, which was '/', and of length == 1.

**Comment by pmcneil** [comment]
Closing because this is so old (sorry). But sounds like you have something in the filter that is trying to index to part of a URL (context path?) that doesn't exist in your deployed environment. Just a guess :-)
