### ISSUE TITLE
grails 3.1.x: No such property: filtersClasses for class: grails.core.DefaultGrailsApplication

### ISSUE THREAD

**Issue by j4y** [pledbrook/grails-shiro#59]
This fork is close to running in grails 3.1.4:
https://github.com/edwardotis/grails-shiro/commit/1507beed1bea72c60ceeaf7728cb5b622ff5ec40

It comes up with an error because grails 3.1 removed filters.  Apparently there is a new way called interceptors.  Any ideas on how to move forward on this or should we stick with 3.0.x?

```
Shiro Configured
ERROR org.springframework.boot.SpringApplication - Application startup failed
org.grails.core.exceptions.GrailsConfigurationException: Error configuring dynamic methods for plugin [shiro:1.2.4-SNAPSHOT]: No such property: filtersClasses for class: grails.core.DefaultGrailsApplication
    at grails.plugins.DefaultGrailsPluginManager.doDynamicMethods(DefaultGrailsPluginManager.java:714)
    at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:227)
    at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
    at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
    at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
    at grails.boot.GrailsApp.run(GrailsApp.groovy:365)
    at grails.boot.GrailsApp.run(GrailsApp.groovy:354)
    at grails.boot.GrailsApp$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
    at grails314shiroexample.Application.main(Application.groovy:8)
Caused by: groovy.lang.MissingPropertyException: No such property: filtersClasses for class: grails.core.DefaultGrailsApplication
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
    at shiro.ShiroGrailsPlugin.doWithDynamicMethods(ShiroGrailsPlugin.groovy:290)
    at org.grails.plugins.DefaultGrailsPlugin.doWithDynamicMethods(DefaultGrailsPlugin.java:750)
    at grails.plugins.DefaultGrailsPluginManager.doDynamicMethods(DefaultGrailsPluginManager.java:711)
    ... 21 common frames omitted
```

**Comment by pmcneil** [comment]
I'm going to have a go to fix and *publish* a new version of this plugin for grails 3.3. 10
